Require 'scikit-learn' instead of 'sklearn'
Collecting fmsne==0.6.0
  Using cached fmsne-0.6.0.tar.gz (283 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/lgatto/disk/cache/basilisk/1.12.0/fmsne/0.2.0/fmsne/lib/python3.9/site-packages (from fmsne==0.6.0) (1.23.5)
Requirement already satisfied: numba in /home/lgatto/disk/cache/basilisk/1.12.0/fmsne/0.2.0/fmsne/lib/python3.9/site-packages (from fmsne==0.6.0) (0.56.4)
Requirement already satisfied: Cython in /home/lgatto/disk/cache/basilisk/1.12.0/fmsne/0.2.0/fmsne/lib/python3.9/site-packages (from fmsne==0.6.0) (0.29.33)
Requirement already satisfied: matplotlib in /home/lgatto/disk/cache/basilisk/1.12.0/fmsne/0.2.0/fmsne/lib/python3.9/site-packages (from fmsne==0.6.0) (3.7.0)
Collecting sklearn (from fmsne==0.6.0)
  Using cached sklearn-0.0.post5.tar.gz (3.7 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package

      If the previous advice does not cover your use case, feel free to report it at
      https://github.com/scikit-learn/sklearn-pypi-package/issues/new
      [end of output]